import {
  Component,
  Input,
  Output,
  EventEmitter,
  OnInit,
  signal,
  computed,
  inject,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormGroup, FormControl, ReactiveFormsModule } from '@angular/forms';
import { GenericRuleEditorComponent } from '../generic-rule-editor/generic-rule-editor.component';
import { DroolsEditorComponent } from '../drools-editor/drools-editor.component';
import { RuleConfigService } from '../../services/rule-config.service';
import { RuleTokenizerService } from '../../services/rule-tokenizer.service';
import { DroolsGeneratorService } from '../../services/drools-generator.service';
import { MultiCriteriaParserService } from '../../services/multi-criteria-parser.service';
import { RuleSuggestorConfig } from '../../models/rule-config.model';
import { RuleToken } from '../../models/token.model';

@Component({
  selector: 'app-side-by-side-container',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    GenericRuleEditorComponent,
    DroolsEditorComponent,
  ],
  templateUrl: './side-by-side-container.component.html',
  styleUrls: ['./side-by-side-container.component.scss'],
})
export class SideBySideContainerComponent implements OnInit {
  private configService = inject(RuleConfigService);
  private tokenizer = inject(RuleTokenizerService);
  private droolsGenerator = inject(DroolsGeneratorService);
  private multiCriteriaParser = inject(MultiCriteriaParserService);

  // Configuration inputs
  @Input() title: string = 'Business Rule Expression - Side by Side';
  @Input() showThemeToggle: boolean = true;
  @Input() showAdvancedMode: boolean = true;
  @Input() showSaveButton: boolean = true;
  @Input() autoGenerateDrools: boolean = true; // Auto-generate on focus
  @Input() layout: 'horizontal' | 'vertical' = 'horizontal';

  // FormGroup for integration
  @Input() formGroup?: FormGroup;
  @Input() logicalRuleControlName: string = 'logicalRule';
  @Input() droolsControlName: string = 'drools';

  // Outputs
  @Output() saved = new EventEmitter<{ logicalRule: string; drools: string }>();
  @Output() themeChanged = new EventEmitter<boolean>(); // true = dark, false = light

  // Internal state
  config = signal<RuleSuggestorConfig | null>(null);
  isDarkTheme = signal(true);
  isAdvancedMode = signal(false);
  lastGeneratedLogicalRule = signal(''); // Track the last logical rule that was used to generate Drools
  
  // Internal form if not provided
  internalForm = new FormGroup({
    logicalRule: new FormControl(''),
    drools: new FormControl(''),
  });

  // Get the form to use (external or internal)
  get activeForm(): FormGroup {
    return this.formGroup || this.internalForm;
  }

  get logicalRuleControl(): FormControl {
    return this.activeForm.get(this.logicalRuleControlName) as FormControl;
  }

  get droolsControl(): FormControl {
    return this.activeForm.get(this.droolsControlName) as FormControl;
  }

  ngOnInit() {
    this.configService.getConfig().subscribe((cfg) => {
      this.config.set(cfg);
      
      // Initialize advanced mode from config
      const savedAdvancedMode = localStorage.getItem('side-by-side-container-advanced-mode');
      if (savedAdvancedMode !== null) {
        this.isAdvancedMode.set(savedAdvancedMode === 'true');
      } else if (cfg.advancedMode?.enabled !== undefined) {
        this.isAdvancedMode.set(cfg.advancedMode.enabled);
      }
    });
    
    // Load theme
    const savedTheme = localStorage.getItem('theme');
    if (savedTheme === 'light') {
      this.isDarkTheme.set(false);
      document.documentElement.setAttribute('data-theme', 'light');
    }
  }

  onLogicalRuleChanged(value: string) {
    // Value already updated via FormControl
  }

  onTokensChanged(tokens: RuleToken[]) {
    // Optional: handle token changes
  }

  onDroolsGenerateRequested() {
    const logicalRule = this.logicalRuleControl.value;
    if (!logicalRule?.trim()) return;

    const cfg = this.config();
    if (!cfg) return;

    // Check if logical rule has changed since last generation
    const hasChanged = logicalRule.trim() !== this.lastGeneratedLogicalRule().trim();
    
    // Only regenerate if the rule has changed OR if Drools is empty
    const currentDrools = this.droolsControl.value?.trim();
    if (!hasChanged && currentDrools) {
      return; // Don't regenerate if rule hasn't changed and Drools exists
    }

    // Check if this is a multi-criteria rule (contains "criteria:" sections)
    const isMultiCriteria = /criteria:/i.test(logicalRule);
    
    let drools: string;
    
    if (isMultiCriteria) {
      // Parse as multi-criteria rule
      const parsed = this.multiCriteriaParser.parseCompleteRule(logicalRule, cfg);
      
      // Convert parsed criteria sections to the format expected by generator
      const criterias = parsed.criteriaSections.map((section, idx) => ({
        sectionId: `section_${idx + 1}`,
        sectionTitle: section.sectionTitle,
        conditions: section.conditions.map((cond, condIdx) => ({
          number: condIdx + 1,
          text: cond
        }))
      }));
      
      // Extract tokens for each criteria condition
      const criteriaTokens = parsed.criteriaSections.map(section => section.tokens);
      
      // Generate multi-criteria Drools
      drools = this.droolsGenerator.generateMultiCriteriaWhenClause(
        1, // rule number
        parsed.mainTokens,
        criterias,
        cfg,
        criteriaTokens // Pass the tokens
      );
    } else {
      // Simple single-line rule
      const tokenized = this.tokenizer.tokenize(logicalRule, cfg);
      drools = this.droolsGenerator.generateWhenClause(tokenized.tokens, cfg);
    }
    
    this.droolsControl.setValue(drools);
    this.lastGeneratedLogicalRule.set(logicalRule); // Track the rule we just generated from
  }

  onSave() {
    const logicalRule = this.logicalRuleControl.value || '';
    const drools = this.droolsControl.value || '';
    
    this.saved.emit({ logicalRule, drools });
  }

  toggleTheme() {
    const newTheme = !this.isDarkTheme();
    this.isDarkTheme.set(newTheme);
    
    if (newTheme) {
      document.documentElement.removeAttribute('data-theme');
      localStorage.setItem('theme', 'dark');
    } else {
      document.documentElement.setAttribute('data-theme', 'light');
      localStorage.setItem('theme', 'light');
    }
    
    this.themeChanged.emit(newTheme);
  }

  toggleAdvancedMode() {
    const newMode = !this.isAdvancedMode();
    this.isAdvancedMode.set(newMode);
    localStorage.setItem('side-by-side-container-advanced-mode', newMode ? 'true' : 'false');
  }

  clearAll() {
    this.logicalRuleControl.setValue('');
    this.droolsControl.setValue('');
  }
}
